LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Rtk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
LOCAL_SRC_FILES := $(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_REQUIRED_MODULES := librtk.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_PREBUILT_LIBS := librtk.so
LOCAL_MODULE_TAGS := optional
include $(BUILD_MULTI_PREBUILT)



